http.host: "0.0.0.0"
xpack.monitoring.elasticsearch.hosts: ["http://elasticsearch:9200"]

path.config: /usr/share/logstash/pipeline
path.logs: /usr/share/logstash/logs

pipeline.workers: 2
pipeline.batch.size: 125
pipeline.batch.delay: 50

queue.type: persisted
queue.max_bytes: 1gb

log.level: info

config.reload.automatic: true
config.reload.interval: 3s

api.enabled: true
api.http.host: "0.0.0.0"
api.http.port: 9600

monitoring.enabled: true