groups:
  - name: system_alerts
    rules:
      - alert: HighCPUUsage
        expr: node:cpu_usage_percent:avg5m > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High CPU usage detected
          description: CPU usage is above 80% for 5 minutes

      - alert: HighMemoryUsage
        expr: node:memory_usage_percent:avg5m > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High memory usage detected
          description: Memory usage is above 85% for 5 minutes

  - name: service_alerts
    rules:
      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Service {{ $labels.job }} is down"
          description: "Service {{ $labels.job }} has been down for more than 1 minute"

      - alert: PostgreSQLHighConnections
        expr: pg_stat_activity_count > pg_settings_max_connections * 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: PostgreSQL high connection usage
          description: PostgreSQL instance has used more than 80% of available connections

      - alert: RedisHighMemory
        expr: redis_memory_used_bytes / redis_memory_max_bytes * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Redis high memory usage
          description: Redis is using more than 80% of its available memory

      - alert: ElasticsearchClusterHealth
        expr: elasticsearch_cluster_health_status > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Elasticsearch cluster health is not green
          description: Elasticsearch cluster health has been yellow or red for 5 minutes